# Generated by Django 4.2.2 on 2023-06-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prohect',
            new_name='Project',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
